"""add status and created_at in table UserService

Revision ID: 3d5c4d64a722
Revises: 5078853933d2
Create Date: 2026-05-18 12:27:48.564307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5c4d64a722'
down_revision: Union[str, Sequence[str], None] = '5078853933d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_services', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('user_services', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_services', 'created_at')
    op.drop_column('user_services', 'status')
    # ### end Alembic commands ###
