"""add notification in table appointment

Revision ID: f8c63acd32c1
Revises: 9952ee91cf72
Create Date: 2026-06-13 13:01:31.481108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c63acd32c1'
down_revision: Union[str, Sequence[str], None] = '9952ee91cf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('notify_at', sa.DateTime(), nullable=True))
    op.add_column('appointments', sa.Column('notified', sa.Boolean(), nullable=True))
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('MANAGE_OWN_USER_SERVICES', 'MANAGE_ALL_USER_SERVICES', 'MANAGE_OWN_APPOINTMENTS', 'MANAGE_ALL_APPOINTMENTS', 'VIEW_CLIENTS', 'MANAGE_ALL_CLIENTS', 'MANAGE_SERVICES', 'MANAGE_OWN_SLOTS', 'MANAGE_ALL_SLOTS', 'MANAGE_OWN_USER', 'MANAGE_ALL_USERS', 'MANAGE_OWN_WORKSCHEDULE', 'MANAGE_ALL_WORKSCHEDULES', 'MANAGE_PERMISSIONS', 'VIEW_OWN_REPORTS', 'VIEW_ALL_REPORTS', 'MANAGE_TENANT', name='permissionrole'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'name',
               existing_type=sa.Enum('MANAGE_OWN_USER_SERVICES', 'MANAGE_ALL_USER_SERVICES', 'MANAGE_OWN_APPOINTMENTS', 'MANAGE_ALL_APPOINTMENTS', 'VIEW_CLIENTS', 'MANAGE_ALL_CLIENTS', 'MANAGE_SERVICES', 'MANAGE_OWN_SLOTS', 'MANAGE_ALL_SLOTS', 'MANAGE_OWN_USER', 'MANAGE_ALL_USERS', 'MANAGE_OWN_WORKSCHEDULE', 'MANAGE_ALL_WORKSCHEDULES', 'MANAGE_PERMISSIONS', 'VIEW_OWN_REPORTS', 'VIEW_ALL_REPORTS', 'MANAGE_TENANT', name='permissionrole'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.drop_column('appointments', 'notified')
    op.drop_column('appointments', 'notify_at')
    # ### end Alembic commands ###
